### ISSUE TITLE
pyqir-evaluator should gracefully fail when bitcode contains unknown external functions

### ISSUE THREAD

**Issue by LaurentAjdnik** [qir-alliance/pyqir#122]
**Describe the bug**

When an LLVM file contains declarations of external functions that are unknown, the evaluator crashes without displaying an error message or raising an Exception.

Issue related to #121.

**To Reproduce**

Use an LLVM file that contains unknown external functions, such as:

```
%String = type opaque

declare %String* @__quantum__rt__bool_to_string(i1)

define void @main() #1 {
entry:
  call %String* @__quantum__rt__bool_to_string(i1 1)
  ret void
}

attributes #1 = { "EntryPoint" }
```

This evaluation does not reach the end and throws no Exception:
```
from pyqir.evaluator import GateLogger, NonadaptiveEvaluator

print("Start")

try:
    NonadaptiveEvaluator().eval("CrashMe.ll", GateLogger())
except Exception as e:
    print("An exception was raised.")

print("End")
```

**Expected behavior**

The evaluator should either:
* Handle them in a transparent manner (if possible)
* Display an error message ("Unsupported function...")
* Raise an exception

**Comment by idavis** [comment]
I think the `bind` function in `qirlib/src/evaluation/runtime.rs` needs to be updated to something like
```rust
    fn bind(module: &Module<'ctx>, ee: &ExecutionEngine<'ctx>) -> Result<(), String> {
        let unknown_functions = module_functions(module).filter(|f| {
            is_extern(*f) && !is_supported_qis_instrinsic(*f) && !is_supported_rt_instrinsic(*f)
        });
        // if collection isn't empty, bubble up error about unsupported functions
```
`module_functions` is defined in `qirlib/src/evaluation/jit.rs` but the other functions don't exist.
