### ISSUE TITLE
GitHub Actions macOS 10.15 runner will be removed by 8/30/22

### ISSUE THREAD

**Issue by samarsha** [qir-alliance/pyqir#139]
The macOS 10.15 runner is deprecated and they're running brownouts to remind people to upgrade: https://github.com/actions/virtual-environments/issues/5583. We should update our macOS version in CI:

https://github.com/qir-alliance/pyqir/blob/d5ea6ef76a1b7fd2a7c7e37a928aa532a8d47f5e/.github/workflows/ci.yml#L57

**Comment by samarsha** [comment]
@idavis should we switch to macos-11 or macos-12?

**Comment by idavis** [comment]
@samarsha Good catch. My initial thought is11. I like to make sure it works on older platforms.
