### ISSUE TITLE
Update dev container to Ubuntu 22.04 base for LLVM 13

### ISSUE THREAD

**Issue by idavis** [qir-alliance/pyqir#142]
When available, update the devcontainer so that that we can install llvm 13 easily as part of the container definition.

**Comment by samarsha** [comment]
Does anyone use the dev container?

**Comment by idavis** [comment]
I did a lot when I was on Windows. Right now it won't run on codespaces since it is too big (even though it was the same image)

**Comment by samarsha** [comment]
If neither of us use it, and it doesn't work, should we just remove it unless someone volunteers to update it?
