### ISSUE TITLE
is `output_name` required to be non-none?

### ISSUE THREAD

**Issue by qci-amos** [qir-alliance/pyqir#160]
https://github.com/qir-alliance/pyqir/blob/0e524e7c54503b886f71d5b10383e8685b768070/pyqir-parser/pyqir/parser/_parser.py#L646-L654

PR #152 introduced `assert output_name is not None`, but this is at odds with the type and the docstring. Is this a bug or is the docstring out of date? A bunch of my unit tests are now crashing because I would use `if inst.output_name:`

**Comment by qci-amos** [comment]
@idavis @samarsha

**Comment by samarsha** [comment]
Yeah, that's a bug, thanks for reporting it. Fixing it now.

**Comment by samarsha** [comment]
I released PyQIR 0.6.1 which contains this fix.
