### ISSUE TITLE
`requiredQubits` and `requiredResults` attributes are not added

### ISSUE THREAD

**Issue by Roland-djee** [qir-alliance/pyqir#164]
Previously, `requiredQubits` and `requiredResults` were generated from `pyqir-generator`. These attributes are important to us to compile further down to the devices. Is it possible to re-add the in the generation ?

**Comment by samarsha** [comment]
These were removed in #147, since QAT can add them itself. But it sounds like you're sending a PyQIR-generated program directly to your internal compiler without going through QAT, is that right? I agree it'd make sense for PyQIR to still be able to add them in that case.
