### ISSUE TITLE
Add words from spell check CI job to cspell.json to cut down on false positive warnings

### ISSUE THREAD

**Issue by idavis** [qir-alliance/pyqir#20]

**Comment by LaurentAjdnik** [comment]
Hi @idavis, I'd be happy to help.

I guess this relates to the words that raised warnings when `link_and_spell_check.yml` is run.

Among others: buildpack, deps, dpkg, eval, clippy, pyclass, pwsh, pymethods, pymodule, qirlib...

BTW, `cspell-action` is called with `config: 'utils/spelling_allowlist.json'` but... I haven't figured out where this file is 😁.

**Comment by LaurentAjdnik** [comment]
> BTW, `cspell-action` is called with `config: 'utils/spelling_allowlist.json'` but... I haven't figured out where this file is 😁.

OK, found it in `.github/workflow-templates` but I assume it should be recreated and updated here, in the current repository.

**Comment by idavis** [comment]
Hi @LaurentAjdnik , thank you for your interest! We are in the process of [setting up the CLA automation](https://github.com/qir-alliance/pyqir#contributing) for external contributions. The `utils/spelling_allowlist.json` comes from the [qir-alliance/.github](https://github.com/qir-alliance/.github/) repository. The build pulls an archive of the main branch and extracts the utils folder locally for the build.

**Comment by LaurentAjdnik** [comment]
Thanks @idavis! Let me know when CLA becomes available and I'll PR something.

**Comment by LaurentAjdnik** [comment]
Hi @cgranade and @idavis. Isn't this issue closed by #49?

**Comment by cgranade** [comment]
@LaurentAjdnik: Not necessarily; #49 reduced the number of false positives substantially, but I didn't yet have the chance to do a more thorough look for other terms to allow-list.

**Comment by samarsha** [comment]
I think that if we want to keep the false positives down, we should consider changing the spellchecking PR status to fail if there are unknown words. Personally I didn't notice that there were spelling issues, because the "check spelling" status gets a green checkmark on the PR.
