### ISSUE TITLE
CI for Apple Silicon

### ISSUE THREAD

**Issue by samarsha** [qir-alliance/pyqir#215]
We need CI for macOS on Apple Silicon (arm64) so that tests and wheels can be automated. We depend on GItHub-hosted runners, so this is blocked by github/roadmap#528 and actions/runner-images#2187.

**Comment by arcondello** [comment]
I believe that you can use emulators to build/test macOS Apple Silicon and manylinux aarch64. Specifically something like pypa's [cibuildwheel](https://github.com/pypa/cibuildwheel).  It actually works with GitHub Actions [out of the box](https://cibuildwheel.readthedocs.io/en/stable/setup/#github-actions). I am not entirely sure how it would interact with the LLVM and Rust install steps, but I would be willing to take a crack at getting it to work if there's interest.

**Comment by idavis** [comment]
Fixed in #260
