### ISSUE TITLE
The parser is not importing 

### ISSUE THREAD

**Issue by PariaNaghavi** [qir-alliance/pyqir#229]
Thank you for the new updates to pyqir! I can't wait to unbox the new features. Currently, I am facing an issue with importing the parser. When attempting to use the [example]( https://github.com/qir-alliance/pyqir/blob/v0.6.2/pyqir-parser/tests/test_parser_api.py) the line `from pyqir.parser import *` raised an error not finding `pyqir.parser` . I have tried pip installing pyqir on MacOS and Linux systems, but the issue persists on both. It is worth noting that there doesn't seem to be any problem with importing the generator module.
**To replicate:**
With pyqir (0.7.0) is installed, try `from pyqir.parser import *` or please see [here]( https://github.com/PariaNaghavi/qir-book/blob/main/qir-book/tutorials/qir-emission/qutip/qir-gen.ipynb)
**Current outcome:**
ModuleNotFoundError: No module named 'pyqir.parser'
ImportError: cannot import name 'parser' from 'pyqir' (/opt/conda/envs/qir-book/lib/python3.9/site-packages/pyqir/__init__.py)
AttributeError: module 'pyqir' has no attribute 'parser'
**Expected outcome:**
 `pyqir.parser` imported with `from pyqir.parser import *`
**Notes:**
I would appreciate any suggestions or insights that might help in addressing this issue. Please let me know if there is any additional information or assistance that I can provide to fix this issue.
**Environment:**
•	OS: MacOS and Linux
•	PyQIR version: 0.7.0
•	Python version: 3.9
![Screen Shot 2023-01-17 at 19 40 38](https://user-images.githubusercontent.com/76576654/213078040-ee7817f1-ff96-4f4e-9742-c1a7bc1c644d.png)

**Comment by idavis** [comment]
Thank you, @PariaNaghavi , for the detailed information. The 0.7 release features the unification of pyqir-generator and pyqir-parser (there is no longer a parser submodule). We made significant changes to the API including many breaking changes. For more information, please read the [upgrade guide](https://www.qir-alliance.org/pyqir/upgrade.html).

The [current version](https://github.com/qir-alliance/pyqir/blob/main/pyqir/tests/test_parser.py) of the parser tests you are attempting to run shows how the revised API is used.
