### ISSUE TITLE
Add functionality to define custom (opaque) data types

### ISSUE THREAD

**Issue by fiona-guerin** [qir-alliance/pyqir#263]
I'm encountering limitations when trying to generate custom opaque data types with PyQIR.  Specifically, inheriting from the `Type` class in Python results in a "no constructor defined" error.

My objective is to generate novel data type definitions within PyQIR, such as a quantum float type. Ideally, I'd like to be able to express these custom types using existing, supported PyQIR types.

Request:
- Document or implement the recommended way to define custom opaque data types within PyQIR?
- Are there any workarounds or alternative approaches to achieve this type of type definition?

**Comment by idavis** [comment]
Hi @fiona-guerin, the only types allowed in QIR are expressed in the PyQIR APIs for generating profile compliant QIR. Custom type definitions like what you've described should be lowered for QIR generation. If you'd like an angle type supported in QIR, I'd recommend filing an issue in the [qir-spec repository](https://github.com/qir-alliance/qir-spec).

To generate the kind of LLVM IR your describing, you could write code in Rust and tell the compiler to emit llvm-ir. If you link against the [qir-runner's QIR runtime](https://github.com/qir-alliance/qir-runner/tree/main/stdlib), you can create programs that will run in a full QIR runtime but not on hardware. 

The separation of the QIR spec/profiles and a full QIR runtime is an important distinction that will be clarified soon in the documentation. For those that want to run QIR programs, not on hardware, one can build or use implementations of the generic QIR runtime.

I can update this issue with a link to the documentation once is it complete.
