### ISSUE TITLE
pyqir_parser exposing too many things on import

### ISSUE THREAD

**Issue by crazy4pi314** [qir-alliance/pyqir#29]
I was working with the parser package, and saw that when you import it, it lists a lot of things that probably shouldn't.
Things like `List` and `Optional`, the underlying Rust interface (things prefixed by "Py"), and the `parser`/`pyqir_parser` also related to internals that probably shouldn't be user facing. 

The example below was generated from using this [conda env](https://github.com/crazy4pi314/qwop/blob/master/environment.yaml), and locally downloading and installing the windows wheels from the [v0.1.0a1 pre-release](https://github.com/qir-alliance/pyqir/releases/tag/v0.1.0a1) on GH.

```
import pyqir_parser as pqp
dir(pqp)

['List',
 'Optional',
 'PyQirBasicBlock',
 'PyQirConstant',
 'PyQirFunction',
 'PyQirInstruction',
 'PyQirModule',
 'PyQirOperand',
 'PyQirParameter',
 'PyQirTerminator',
 'PyQirType',
 'QirAShrInstr',
 'QirAddInstr',
 'QirAndInstr',
 'QirArrayType',
 'QirBlock',
 'QirBrTerminator',
 'QirCallInstr',
 'QirCondBrTerminator',
 'QirConstant',
 'QirDoubleConstant',
 'QirDoubleType',
 'QirFAddInstr',
 'QirFCmpInstr',
 'QirFDivInstr',
 'QirFMulInstr',
 'QirFNegInstr',
 'QirFRemInstr',
 'QirFSubInstr',
 'QirFunction',
 'QirICmpInstr',
 'QirInstr',
 'QirIntConstant',
 'QirIntegerType',
 'QirLShrInstr',
 'QirLocalOperand',
 'QirModule',
 'QirMulInstr',
 'QirNamedStructType',
 'QirNullConstant',
 'QirOpInstr',
 'QirOperand',
 'QirOrInstr',
 'QirParameter',
 'QirPhiInstr',
 'QirPointerType',
 'QirQirCallInstr',
 'QirQisCallInstr',
 'QirQubitConstant',
 'QirQubitType',
 'QirResultConstant',
 'QirResultType',
 'QirRetTerminator',
 'QirRtCallInstr',
 'QirSDivInstr',
 'QirSRemInstr',
 'QirShlInstr',
 'QirStructType',
 'QirSubInstr',
 'QirSwitchTerminator',
 'QirTerminator',
 'QirType',
 'QirUDivInstr',
 'QirURemInstr',
 'QirUnreachableTerminator',
 'QirVoidType',
 'QirXorInstr',
 'Tuple',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'module_from_bitcode',
 'parser',
 'pyqir_parser']
```

**Comment by bettinaheim** [comment]
Assigning to @samarsha for a follow up. @swernli Could you weigh in here?

**Comment by samarsha** [comment]
This is a consequence of how Python imports work... the imported module or module members are simply added to the parent module, and are treated the same as locally defined module members. It affects other Python libraries, for example you can access `Path`, `sys`, `argparse`, and `json` which are all imports in `json.tool`.:

https://github.com/python/cpython/blob/47422a852de14a8ec11d058136c7c864d2cc7fc9/Lib/json/tool.py#L13-L16

```python
>>> import json.tool
>>> dir(json.tool)
['Path', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'argparse', 'json', 'main', 'sys']
```

There are ways I know of to improve this but they are fairly burdensome on the library author (us). We could require all imports to be renamed with an underscore prefix, like

```python
import foo as _foo
from bar import bar1 as _bar1, bar2 as _bar2
```

Or you could import them normally but override a module's `__dir__` and `__getattr__`, use `del` to remove the imports at the bottom of the module, or something like that.

However, it seems like a lot of (most?) Python libraries don't do anything about this. The module's documentation should be the definitive list of exports from the module that users can depend on.
