### ISSUE TITLE
unwrap() calls can propagate to Python PanicExceptions

### ISSUE THREAD

**Issue by cgranade** [qir-alliance/pyqir#31]
In some cases, calls to `unwrap` can result in `PanicExceptions` propagating out to Python callers, but without actionable error messages to help users solve possible issues.

For example:

```python
>>> import pyqir_generator as pqg
>>> builder.add_quantum_register("qr", 3)
>>> builder.add_classical_register("cr0", 1) # ← typo here!
>>> builder.h("qr0")
>>> builder.m("qr0", "cr0")
>>> builder.get_ir_string()
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
~\...\1016496886.py in <module>
----> 1 builder.get_ir_string()

~\...\lib\site-packages\pyqir_generator\builder.py in get_ir_string(self)
    235         Returns the modeled circuit as an LLVM IR module (human readable) string.
    236         """
--> 237         return self.pyqir.get_ir_string()
    238 
    239     def get_bitcode_base64_string(self):

PanicException: called `Option::unwrap()` on a `None` value
```

In this example, the typo in the call to `add_classical_register` is not easy to find, as the eventual error message does not mention that register name was incorrect.

**Comment by samarsha** [comment]
In the new API, it's still possible to get a panic by mixing qubits/results from different modules:

```python
from pyqir.generator import BasicQisBuilder, SimpleModule
mod1 = SimpleModule("mod", 1, 0)
mod2 = SimpleModule("mod", 2, 0) 
qis1 = BasicQisBuilder(mod1.builder)
qis1.x(mod2.qubits[1])
print(mod1.ir())
```

The panic message was made more informative recently, but is more confusing with the new API, since "qubit1" doesn't appear in the user's code:

```
thread '<unnamed>' panicked at 'Qubit qubit1 not found.', qirlib\src\generation\qir\instructions.rs:23:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyo3_runtime.PanicException: Qubit qubit1 not found.
```

**Comment by samarsha** [comment]
This particular issue is fixed - mixing values from different contexts is raises a normal Python exception now. There might be more panics in other places, but I think separate issues specifically for those should be filed instead.
