### ISSUE TITLE
Minimize QIR profile and update the used QIS

### ISSUE THREAD

**Issue by samarsha** [qir-alliance/pyqir#33]
PyQIR Generator creates QIR modules with an entry point that loops through an array of measurement results, converts them to strings, and prints them to standard output. However, not all hardware backends support arrays, strings, or console output. It should be possible to generate modules without the built-in measurement result output code.

**Comment by idavis** [comment]
- [ ] Change API to generate base profile calls
- [ ] Create constant/type declarations on demand
- [ ] Create IR declarations for calls on demand
- [ ] Add ability to add sting/array/interop convenience calls with stdout
