### ISSUE TITLE
QirBlock does not have a stable hash

### ISSUE THREAD

**Issue by crazy4pi314** [qir-alliance/pyqir#39]
In the definition for the `QirBlock` class, when you ask for the list of instructions it constructs a new list each time. This makes the hash unstable then when iterating through the functions of a block at different times. It seems like the `QirBlock` should either be unhashable or have it pass on the hash from the block. 

https://github.com/qir-alliance/pyqir/blob/c68d735331158f655db965daae8d925b8a1b975c/pyqir-parser/pyqir_parser/parser.py#L723

**Comment by swernli** [comment]
This is a good find, thanks! There may be a few other places that follow this pattern and would result in similarly undesirable hash behavior. We should review and update this pattern anywhere it appears.
