### ISSUE TITLE
Avoid installing Python build dependencies into a non-virtual environment

### ISSUE THREAD

**Issue by samarsha** [qir-alliance/pyqir#55]
In eng/psakefile.ps1, we install tox using `python -m pip install tox`. We run this command without creating a virtual environment ourselves, so it installs into whatever environment the build script is run from. We should avoid automatically installing things into the user's environment, e.g. by creating our own virtual environment first, or by requiring tox to already be installed.

**Comment by idavis** [comment]
Fixed in #119
