### ISSUE TITLE
pyqir_generator README.md is out of date

### ISSUE THREAD

**Issue by guenp** [qir-alliance/pyqir#61]
It looks like this readme is outdated: https://github.com/qir-alliance/pyqir/tree/main/pyqir-generator#examples

And should be updated with the contents of this file: https://gist.github.com/samarsha/23ee1e3178f12d387c08429a99bb1e4b

**Comment by bettinaheim** [comment]
@samarsha Could you please take a look? Let's update all documentation, including readmes and examples as part of the feature work - I think this may have been missed accidentally when merging your API updates.
