### ISSUE TITLE
PyQIR generator documentation is incomplete

### ISSUE THREAD

**Issue by samarsha** [qir-alliance/pyqir#62]
The documentation at https://qir-alliance.github.io/pyqir/api-reference/generator.html is missing parameters, types and docstrings. This is likely because Sphinx can't read .pyi files for autodoc sections: sphinx-doc/sphinx#7630

**Comment by LaurentAjdnik** [comment]
I looked around but indeed found no way to generate docs from `.pyi` files with Sphinx.

But I feel like this is possible from "docstrings" included in the Rust source itself.

The Fastobo project seems to have achieved this.

For instance, with the `load_graph()` function:
* [Rust source with docstring](https://github.com/fastobo/fastobo-py/blob/f59d7e5c7782eb9829aaec81066593a7c01e8d78/src/py/mod.rs#L295)
* [Doc generation](https://github.com/fastobo/fastobo-py/blob/master/docs/api/index.rst)
* [Resulting doc](https://fastobo.readthedocs.io/en/latest/api/index.html#fastobo-load-graph)

Their `conf.py` file is [here](https://github.com/fastobo/fastobo-py/blob/master/docs/conf.py).
