### ISSUE TITLE
Support external functions in generator

### ISSUE THREAD

**Issue by samarsha** [qir-alliance/pyqir#63]
PyQIR Generator should support adding external function declarations to a module and emitting LLVM call instructions for them using the builder. The initial version of the feature will probably support only external functions with a void return type. That will enable custom quantum instruction sets and state-changing utility functions.

A draft PR with an initial implementation is available: #54

There are a few different ideas for how the API can be designed:

## 1. Declare function before calling

`SimpleModule` could have a method like `add_external_function(name, types)` that returns a wrapped LLVM function value. `Builder` could have a method like `call(function, args)` that takes the function value and a list of arguments.

```python
module = SimpleModule(...)
my_function = module.add_external_function("my_function", Qubit)
module.builder.call(my_function, module.qubits[0])
```

Pros:
- Simple and explicit API with minimal magic under the hood
- Close to LLVM and easy to evolve into a general LLVM call API (e.g. with return types)
- Good support for mypy and code completion

Cons:
- Verbose

## 2. Automatically declare function on first call

There would be no explicit method to add a function - it would happen automatically the first time `call(name, args)` is used with a new function name. The type of the external function would be inferred from the type of the arguments.

```python
module = SimpleModule(...)
module.builder.call("my_function", module.qubits[0])
```

Pros:
- Simpler for currently supported cases (statically known function value with void return type)

Cons:
- Return type can't easily be inferred in the future
- Very dynamic; typos in function name string or issues in inferred argument types could lead to hard-to-debug errors. Because an LLVM function definition is implicily added the first time `call` is used, the first call will always succeed but subsequent calls may fail if the argument types are different.

## 3. Automatically declare function on first call with sugar

A sugared version of option 2 would be to define `__getattr__` on `Builder` that would handle unknown method names. For example, `builder.my_external_function(args)` would be converted to `builder.call("my_external_function", args)`.

```python
module = SimpleModule(...)
module.builder.my_function(module.qubits[0])
```

Pros:
- Very concise

Cons:
- Does not work as well with Python tooling (type checking, code completion)
- Function names can clash with other method names on `Builder`

## Future evolution

We should consider how the chosen API will evolve into a more general LLVM call instruction API. In particular, the options above all have the `call` method on `Builder`, but `Builder` is not specific to the basic QIR profile. So if we choose a simplified `call` API, it may stick around alongside the more general API.

Some features we should consider for future evolution:

- Arguments may be any LLVM value (e.g. referring to a previous instruction result), not just Python values that are converted into LLVM constants.
- Functions could have a non-void return type.
- The function value may not be statically known (but this may require a different API for [QIR callables](https://github.com/qir-alliance/qir-spec/blob/main/specification/v0.1/2_Callables.md)).

**Comment by guenp** [comment]
Thanks @samarsha  for the clear overview! My preference would be to support both (1) and (2), e.g.

```python
module = SimpleModule(...)
my_function = module.add_external_function("my_function", Qubit)
module.builder.call(my_function, module.qubits[0])
```

and
```python
module = SimpleModule(...)
module.builder.call(name="my_function", module.qubits[0]) # note that I added the keyword `name` here to disambiguate from the other `function` argument
```

I like having the option of being able to add a function without having to declare it separately. (3) is a bit too "magical" for me, it isn't clear from the get-go that `my_function` is a valid method on `module.builder`. Having to explicitly specify the name seems better to me (["explicit is better than implicit"](https://www.python.org/dev/peps/pep-0020/)).

Should `module.builder.call` also support keyword arguments in addition to positional args? e.g.

```python
module = SimpleModule(...)
my_function = module.add_external_function("my_function", my_qubit=Qubit)
module.builder.call("my_function", my_qubit=module.qubits[0])
```

**Comment by samarsha** [comment]
Thanks @guenp.

> ```python
> module.builder.call(name="my_function", module.qubits[0]) # note that I added the keyword `name` here to disambiguate from the other `function` argument
> ```
>
> I like having the option of being able to add a function without having to declare it separately.

I don't think Python lets you have a positional argument `module.qubits[0]` after a keyword argument `name="my_function"`. The function type would need to use a keyword argument as well or be placed before the function name. I'm also not sure that it would be possible to enforce in mypy that either `name="..."` or `function_value` is specified, but not both - so it would be a runtime error to specify both or neither.

The behavior between the two modes is different enough that I would prefer to give them different method names if we supported both. But I'm also not really sure name to use for the version of `call` that automatically creates a function if it doesn't exist.

> (3) is a bit too "magical" for me, it isn't clear from the get-go that `my_function` is a valid method on `module.builder`. Having to explicitly specify the name seems better to me (["explicit is better than implicit"](https://www.python.org/dev/peps/pep-0020/)).

Yes, I totally agree - I have the same concerns about option 3 and would also prefer not to go forward with it.

> Should `module.builder.call` also support keyword arguments in addition to positional args? e.g.
> 
> ```python
> module = SimpleModule(...)
> my_function = module.add_external_function("my_function", my_qubit=Qubit)
> module.builder.call("my_function", my_qubit=module.qubits[0])
> ```

I don't think there's a mechanism in LLVM for parameter names of externally linked functions - their signature only supports positional arguments. So, we could still do it, but we'd have to store and manage the parameter names ourselves, and they wouldn't be part of the emitted QIR. For simplicity I would recommend skipping this for now but we could revisit it later.

**Comment by samarsha** [comment]
Another thing we should consider is how to precisely represent the LLVM type of the function in Python. For example in the LLVM/qirlib API you would do something like:

```rust
let void_type = context.void_type();
let qubit_type = generator.qubit_type().ptr_type(AddressSpace::Generic);
let fn_type = void_type.fn_type(&[qubit_type], false);
module.add_function("my_function", fn_type, Some(Linkage::External));
```

We don't expose the context or code generator in Python so this would need to be simplified, but a close approximation is maybe something like one of these (in order from most to least verbose):

```python
# add_external_function takes two arguments (name and type)
module.add_external_function("my_function", Function([Qubit], Void))

# add_external_function takes three arguments (name, param types, and return type)
module.add_external_function("my_function", [Qubit], Void)
module.add_external_function("my_function", [Qubit], None)

# default value return_type=None
module.add_external_function("my_function", [Qubit])

# if we don't support a return type or require that it's a keyword argument, we could use *args
module.add_external_function("my_function", Qubit)
```

**Comment by samarsha** [comment]
@idavis brought up a good point in a discussion together: option 2 doesn't have a way to infer the different sized integer types (`i8`, `i32`, `i64`, etc.) because they all correspond to Python `int`. This is a problem because it would cause PyQIR to create an external function declaration with the wrong integer size, which won't link correctly.

So we need to have option 1 and explicitly sized integer types exposed in Python, for example:

```python
my_function = module.add_external_function("my_function", FunctionType([IntType(32), QubitType], VoidType))
# int(5) implicitly converted to LLVM i32
builder.call(my_function, [5, q])
```

For the same reason I'm also inclined to not support option 2 (at least for now), because we would be forced to assume a specific integer type (e.g. `i64`) which will likely be wrong.

**Comment by samarsha** [comment]
> For the same reason I'm also inclined to not support option 2 (at least for now), because we would be forced to assume a specific integer type (e.g. `i64`) which could likely be wrong when linked against the user's external functions.

The flip side to this is if we require explicitly-typed constant values, like the LLVM API does - for example instead of `5`, it would be something like `IntType(32).const(5)` which is of a custom type `IntValue` that includes the size. I think that is more verbose than requiring an explicit function declaration though. Although it's possible we might need to add syntax like that eventually, depending on what LLVM instructions we support and whether the constant types can be inferred.
