### ISSUE TITLE
Add suggested citation metadata to README.md and/or conceptual docs

### ISSUE THREAD

**Issue by cgranade** [qir-alliance/pyqir#69]
For use from academic papers, it would be nice if there was an official suggestion as to what BibTeX source to use in citing PyQIR packages.

Examples in other Python packages for scientific computing use:

- https://qutip.org/citing.html
- https://numpy.org/citing-numpy/
- https://qiskit.org/textbook/preface.html#Contributors
- https://toqito.readthedocs.io/en/latest/getting_started.html#citing
- http://docs.qinfer.org/en/latest/intro.html#citing-qinfer
- https://scikit-learn.org/stable/about.html#citing-scikit-learn

**Comment by samarsha** [comment]
Personally, I would rather wait until this becomes a real request instead of preempting it.

**Comment by crazy4pi314** [comment]
I don't think it makes sense to wait, it's the kind of thing if folks can't find it right away they will just skip citing it and not ask...

**Comment by samarsha** [comment]
Is there any reason to believe that someone would want to cite PyQIR in an academic paper? PyQIR is not particularly original (it's just an LLVM wrapper) so that would surprise me, and I'm not particularly bothered if someone uses it without an official citation.
