### ISSUE TITLE
[pyqir-generator] Support for identity gate

### ISSUE THREAD

**Issue by guenp** [qir-alliance/pyqir#74]
A very useful gate to have as part of basic gateset is the identity gate. On hardware, it can be used to construct an intentional time delay, and in software, it can be useful for debugging purposes.

Qiskit, for instance, supports the identity gate as part of the basic gateset and cannot be optimized or unrolled:
https://qiskit.org/documentation/stubs/qiskit.circuit.library.IGate.html#igate

Currently, the pyqir `BasicQisBuilder` does not support an identity gate; instead, one could use two subsequent X gates. However, these could be optimized out at later stages; it would be good to have a dedicated Identity gate for the aforementioned purposes.

**Comment by LaurentAjdnik** [comment]
Hi @guenp! I would love trying to contribute to this one. It will help me better understand the whole architecture.

**Comment by guenp** [comment]
Thanks @LaurentAjdnik  that sounds great! I think we'd need to add it to `qirlib` first, then make it available to Python via the pyo3 interop. Some relevant files to look at are https://github.com/qir-alliance/pyqir/blob/main/qirlib/src/generation/interop.rs and https://github.com/qir-alliance/pyqir/blob/main/pyqir-generator/src/python.rs

I wanted to check with @idavis first though, on if adding an identity gate to the instruction set doesn't violate any design principles.

**Comment by bettinaheim** [comment]
@LaurentAjdnik @guenp Coming back to this, it should now actually be much easier to do this, see also https://github.com/qir-alliance/pyqir/issues/63. @samarsha Is there documentation and/or an example for how to use the forward declaration mechanism to e.g. define an identity gate and generate a call to it?

**Comment by samarsha** [comment]
Here is an example: https://github.com/qir-alliance/pyqir/blob/main/examples/generator/external_functions.py

**Comment by bettinaheim** [comment]
I believe we can close this issue and will go ahead and do that. Please reopen if this doesn't meet your need.
